apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagerservice
spec:
  selector:
    matchLabels:
      app: usermanagerservice
  template:
    metadata:
      labels:
        app: usermanagerservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: changjjjjjjjj/raffle-user-manager:v0.0.1-alpha
          imagePullPolicy: Always
          ports:
            - containerPort: 3550
---
apiVersion: v1
kind: Service
metadata:
  name: usermanagerservice
spec:
  type: NodePort
  selector:
    app: usermanagerservice
  ports:
    - name: server
      port: 3550
      nodePort: 30250
      targetPort: 3550