name: theraffle
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  test_lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.43
          args: -v -E gofmt -E golint -E gocyclo -E misspell --timeout 1h0m0s
  deploy-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ test_lint ]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
      - name: build
        run: |
          docker login -u=changjjjjjjjj -p=${{ secrets.DOCKER_HUB_PASSWORD }}
          REPO_USER_SERVICE=changjjjjjjjj/raffle-user-service
          IMG_USER_SERVICE=${REPO_USER_SERVICE}:${GITHUB_REF#refs/tags/}
          docker build . -t ${IMG_USER_SERVICE} -f Dockerfile

          docker tag ${IMG_USER_SERVICE} ${REPO_USER_SERVICE}:latest

          docker push ${IMG_USER_SERVICE}
          docker push ${REPO_USER_SERVICE}:latest