name: theraffle
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  test_lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: set golint
        run: go get -u golang.org/x/lint/golint
      - name: test lint
        run: golint ./...
