name: theraffle
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  test_lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: golangci/golangci-lint-action@v2.2.1
        with:
          version: v1.29
          args: -v -E gofmt -E golint -E gocyclo -E misspell --timeout 1h0m0s
